---
- name: Update system
  yay:
    update_cache: yes
    upgrade: yes

- name: Install base-devel (Manjaro)
  become: true
  package:
    name: base-devel
    state: latest

- name: Ensure git is installed
  become: true
  package:
    name: git
    state: present
