---
- name: Update system (Debian)
  become: true
  apt:
    upgrade: "yes"
    update_cache: true

- name: Ensure basic applications are installed
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - build-essential
    - curl
    - gnupg
