---
- import_tasks: baseline_debian.yml
  when: ansible_facts.os_family == "Debian" or
        ansible_facts.os_family == "Pop!_OS"

- import_tasks: baseline_manjaro.yml
  when: ansible_facts.os_family == "Archlinux"
