---
- name: Generate git ssh key
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ playbook_dir }}/vars/ssh_vars.yml"
  tasks:
    - name: Generate keypair
      community.crypto.openssh_keypair:
        path: "{{ ssh_path }}"
        size: "{{ ssh_size }}"
        type: "{{ ssh_type }}"
        state: present
