---
- name: Setup Manjaro system
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - "{{ playbook_dir }}/vars/external_vars.yml"
  roles:
    - alacritty
    - nerd_fonts
    - tmux
    - oh_my_zsh
    - nvm
    - nvim
