---
- import_tasks: install_direnv_debian.yml
  when: ansible_facts.os_family == "Debian"

- import_tasks: install_direnv_arch.yml
  when: ansible_facts.os_family == "Archlinux"

- name: Setup direnv hook
  lineinfile:
    path: $HOME/.profile
    line: 'eval "$(direnv hook zsh)"'
