---
- import_tasks: install_brave_debian.yml
  when: ansible_facts.os_family == "Debian" or
        ansible_facts.os_family == "Pop!_OS"

- import_tasks: install_brave_arch.yml
  when: ansible_facts.os_family == "Archlinux"
