---
- import_tasks: setup_chrome_debian.yml
  when: ansible_facts.os_family == "Debian" or
        ansible_facts.os_family == "Pop!_OS"

- import_tasks: setup_chrome_manjaro.yml
  when: ansible_facts.os_family == "Archlinux"
